name: Build Test

on:
  push:
    branches: [ main ]  # 当推送到main分支时触发
    tags:
      - 'v*'  # 当推送v开头的tag时触发

# 添加必要的权限
permissions:
  contents: write
  actions: write
  checks: write
  packages: write

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整的git历史
    
    - name: List files after checkout
      run: |
        echo "Current directory contents:"
        dir /s
        echo "Checking if spec file exists:"
        if exist TingQuanChanger.spec (
          echo "Spec file found"
          type TingQuanChanger.spec
        ) else (
          echo "Spec file not found"
          exit 1
        )
      shell: cmd
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # 显示Python和pip版本
        python --version
        pip --version
        # 安装依赖并显示详细信息
        pip install -r requirements.txt -v
        pip install pyinstaller -v
        
    - name: Build Windows
      run: |
        # 确保spec文件存在并显示内容
        dir
        type TingQuanChanger.spec
        echo "Starting PyInstaller build with detailed output..."
        python -m PyInstaller --noconfirm --log-level DEBUG TingQuanChanger.spec > build_output.log 2>&1
        type build_output.log
        
        echo "Checking build output..."
        dir dist /s
        
        cd dist
        powershell -Command {
          $exeName = "听泉CursorPro换号工具.exe"
          $dirName = "听泉CursorPro换号工具"
          
          if (Test-Path $exeName) {
            echo "Build output found: Single file mode"
            New-Item -ItemType Directory -Path $dirName -Force
            Move-Item $exeName $dirName -Force
            Copy-Item ..\README.md $dirName -Force
            Copy-Item ..\requirements.txt $dirName -Force
          } else {
            echo "Build failed - executable not found"
            Get-ChildItem -Recurse
            exit 1
          }
        }
        cd ..
        
    - name: Create ZIP archive
      shell: powershell
      run: |
        echo "Creating ZIP archive..."
        cd dist
        Get-ChildItem -Recurse
        Compress-Archive -Path "听泉CursorPro换号工具" -DestinationPath ..\听泉CursorPro换号工具-Windows.zip -Force
        cd ..
        if (Test-Path "听泉CursorPro换号工具-Windows.zip") {
          echo "ZIP file created successfully"
          Get-Item "听泉CursorPro换号工具-Windows.zip"
        } else {
          echo "Error: ZIP file creation failed"
          exit 1
        }
        
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: 听泉CursorPro换号工具-Windows
        path: 听泉CursorPro换号工具-Windows.zip
        retention-days: 5
        
    - name: Upload Build Logs
      if: always()  # 即使前面的步骤失败也上传日志
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: build_output.log 